django_task/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('minisite.urls')),
]

minisite/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views

from . import views

app_name = 'minisite'
urlpatterns = [
    # Index
    path('', views.index, name='index'),

    # Login / Logout
    path('login',  auth_views.login,  name='login'),
    path('logout', auth_views.logout, name='logout'),

    # Add / Edit views
    path('add', views.node_add_edit, name='add'),
    path('<path:parent_path>/add', views.node_add_edit, name='node_add_subnode'),
    path('<path:node_path>/edit',  views.node_add_edit, name='node_edit'),

    # Sic: a catch-all url pattern. Keep it last!
    path('<path:node_path>', views.node_detail, name='node_detail'),
]

minisite/models.py
from django.core.validators import RegexValidator
from django.db import models
from django.http import Http404
from django.urls import resolve
from treebeard.mp_tree import MP_Node

validate_unicode_slug_no_dashes = RegexValidator(
    r'^\w+\Z',
    "Enter a valid 'slug' consisting of Unicode letters, numbers, or underscores.",
    'invalid'
)


class Node(MP_Node):
    slug = models.SlugField(max_length=100, allow_unicode=True, validators=[validate_unicode_slug_no_dashes])
    title = models.CharField(max_length=1024)
    content = models.TextField()
    node_order_by = ['slug']

    @classmethod
    def get_by_path(cls, path: str):
        """
        Get Node by full path.
        Can throw MultipleObjectsReturned if DB is inconsistent
        :param path: path string like 'foo/bar/baz'
        :return: Node instance or None
        """
        if not path:
            return None

        try:
            next_node = None
            for path_component in path.split('/'):
                if not next_node:
                    # Explicitly find the root node, since the syntax is different
                    next_node = cls.get_root_nodes().get(slug=path_component)
                else:
                    next_node = next_node.get_children().get(slug=path_component)
            return next_node

        except cls.DoesNotExist:
            return None

    @classmethod
    def get_by_path_or_404(cls, path: str):
        """
        Get Node by full path or raise Http404
        Can throw MultipleObjectsReturned if DB is inconsistent
        :param path: path string like 'foo/bar/baz'
        :return: Node instance
        """
        n = cls.get_by_path(path)
        if n:
            return n
        else:
            raise Http404('Node not found')

    def get_descendants_annotated_list(self):
        """
        Gets __class__.get_annotated_list() for descendants
        A shortcut to use in templates
        :return: annotated tree branch of element's descendants
        """
        return self.get_annotated_list_qs(self.get_descendants()) if not self.is_leaf() else []

    def get_path(self):
        """
        Get full path of this instance
        :return: path string like 'foo/bar/baz'
        """
        if self.pk:
            path_elements = [x.slug for x in self.get_ancestors()] + [self.slug]
            return '/'.join(path_elements)
        else:
            return ''

    @classmethod
    def get_projected_path(cls, ref_node_id, position, slug):
        """
        Get full path Node will have after NodeForm is saved with given parameters
        :return: path string like 'foo/bar/baz'
        """
        if not ref_node_id:
            return slug

        ref_node = Node.objects.get(pk=ref_node_id)
        if position == 'sorted-sibling':
            # Have to try harder to find parent
            if ref_node.is_root():
                return slug
            ref_node = ref_node.get_parent()

        return '/'.join([ref_node.get_path(), slug])

    def is_acceptable_path(self, path: str):
        if not path:
            return False
        # If it's my path, it's acceptable
        if path == self.get_path():
            return True

        # Find a view for this path
        resolved_path = resolve('/' + path)
        if resolved_path.view_name != 'minisite:node_detail':
            # If path is reserved for any view but node_detail
            return False
        else:
            # if it's a node detail url - check that node with this path does not exist
            return not self.get_by_path(path)

    def __str__(self):
        return "[{}] {}".format(self.get_path(), self.title)

minisite/forms.py
from django.core.exceptions import ValidationError
from treebeard.forms import movenodeform_factory

from .models import Node

# Subclassing MoveNodeForm directly is discouraged,
# since special care is needed to handle excluded fields, and these change depending on the tree type
MP_Form = movenodeform_factory(Node)


class NodeForm(MP_Form):
    def clean(self):
        # Check if slug may be used
        slug = self.cleaned_data.get('slug', '')
        position = self.cleaned_data.get('_position', None)
        ref_node_id = self.cleaned_data.get('_ref_node_id', None)
        projected_path = self.instance.get_projected_path(ref_node_id, position, slug)
        if not self.instance.is_acceptable_path(projected_path):
            raise ValidationError("This slug can not be used: path /{} is unavailable".format(projected_path))

        return super(self.__class__, self).clean()

minisite/views.py
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, redirect
from django.urls import reverse_lazy

from .forms import NodeForm
from .models import Node


def index(request):
    """
    Retrieves the index (home) page
    """
    return render(request, 'nodes/index.html', {
        'nodes_list': Node.get_annotated_list(),
    })


def node_detail(request, node_path):
    current_node = Node.get_by_path_or_404(node_path)
    return render(request, 'nodes/detail.html', {
        'node': current_node,
        'subnodes': current_node.get_descendants_annotated_list()
    })


@login_required(login_url=reverse_lazy('minisite:login'))
def node_add_edit(request, node_path=None, parent_path=None):
    """
    Shows / Validates add/edit Node form
    @todo Add user permissions validation

    :param node_path: Node path to edit. default:None to create a new Node
    :param parent_path: Parent Node path to prefill the form. Only used if node_path=None
    """
    if node_path:
        # Editing existing node
        current_node = Node.get_by_path_or_404(node_path)
        initial = {}
        title = "Edit node <strong>{}</strong>".format(current_node.title)

    elif parent_path:
        # Adding a sub-node
        parent_node = Node.get_by_path_or_404(parent_path)
        # Pre-fill the form with correct node position, but allow to change it later
        initial = {'_ref_node_id': parent_node.pk, '_position': 'sorted-child'}
        current_node = Node()
        title = "Add sub-node for <strong>{}</strong>".format(parent_node.title)

    else:
        # Adding a new root node
        current_node = Node()
        initial = {}
        title = "Add a new node"

    form = NodeForm(request.POST or None, instance=current_node, initial=initial)

    if request.POST and form.is_valid():
        saved_node = form.save()
        # Be careful with node now because http://django-treebeard.readthedocs.io/en/latest/caveats.html#raw-queries
        return redirect('minisite:node_detail', node_path=saved_node.get_path())

    return render(request, 'nodes/edit.html', {
        'form': form,
        'title': title
    })

minisite/templates/base.html
{% extends 'bootstrap4/bootstrap4.html' %}
{% load bootstrap4 %}


{% block bootstrap4_extra_head %}
    <title>{% block page_title %}Django Minisite{% endblock %}</title>
{% endblock %}


{% block bootstrap4_content %}
    <nav class="navbar navbar-light navbar-expand-xs bg-light">
        <div class="container">

            <a class="navbar-brand" href="{% url 'minisite:index' %}">
                <img src="https://www.djangoproject.com/m/img/logos/django-logo-negative.svg"
                     height="30" class="d-inline-block align-top" alt="Django" style="margin-right: .5rem;">
                Django test site
            </a>

            {% if user.is_authenticated %}
                <div>
                    <span class="navbar-text" style="margin-right: .5rem;">Welcome, <strong>{{ user.username }}</strong></span>
                    {% if user.is_superuser %}
                        <a class="btn btn-sm btn-primary align-baseline" href="{% url 'admin:index' %}">Admin</a>
                    {% endif %}
                    <a class="btn btn-sm btn-secondary align-baseline" href="{% url 'minisite:logout' %}">Logout</a>
                </div>
            {% else %}
                <span class="navbar-text">Please <a href="{% url 'minisite:login' %}">log in</a></span>
            {% endif %}
        </div>
    </nav>

    <div class="container" style="margin-top: 5%; margin-bottom: 5rem;">
        {% block nav %}{% endblock %}

        <h2 class="page-header" style="margin-bottom: .5rem;">{% block title %}{% endblock %}</h2>

        {% autoescape off %}{% bootstrap_messages %}{% endautoescape %}

        {% block content %}(no content){% endblock %}
    </div>
{% endblock %}

minisite/templates/nodes/detail.html
{% extends 'base.html' %}
{% load bootstrap4 %}
{% load wikify %}


{% block page_title %}{{ node.title }}{% endblock %}
{% block title %}{{ node.title }}{% endblock %}

{% block nav %}
    {% url 'minisite:index' as home_url %}

    <nav aria-label="breadcrumb" role="navigation" style="margin-bottom: 2rem;">
        <ol class="breadcrumb">
            <li class="breadcrumb-item"><a href="{{ home_url }}">Home</a></li>
            {% for ancestor in node.get_ancestors %}
                <li class="breadcrumb-item parent-{{ forloop.counter }}" id="id{{ ancestor.pk }}">
                    <a href={% url 'minisite:node_detail' ancestor.get_path %}>{{ ancestor.title }}</a>
                </li>
            {% endfor %}
            <li class="breadcrumb-item active" aria-current="page">{{ node.title }}</li>
        </ol>
    </nav>
{% endblock %}


{% block content %}
    <p class="node-content">{{ node.content|wikify|safe }}</p>

    <p style="margin-bottom: 3rem; text-align: right;">
        <a class="btn btn-secondary" href="{% url 'minisite:node_edit' node.get_path %}">Edit</a>
    </p>

    <div class="node_tree-container">
        <h3 class="node_tree-header">Sub-nodes:</h3>
        {% if not node.is_leaf and subnodes %}
            <!-- Show subnodes -->
            {% include "nodes/fragment-node_tree.html" with nodes=subnodes only %}
        {% endif %}
        <a class="btn btn-primary" href="{% url 'minisite:node_add_subnode' node.get_path %}">Add sub-node</a>
    </div>

{% endblock %}

minisite/templates/nodes/edit.html
{% extends 'base.html' %}
{% load bootstrap4 %}

{% block page_title %}{{ title|striptags }}{% endblock %}
{% block title %}{{ title|safe }}{% endblock %}

{% block content %}

    <form role="form" class="form-horizontal" method="post">
        {% csrf_token %}
        {% bootstrap_form form layout="horizontal" %}
        {% buttons submit='OK' layout='horizontal' %}{% endbuttons %}
    </form>

{% endblock %}

minisite/templates/nodes/fragment-node_tree.html
{% if nodes %}
    <div class="node_tree">
        {% for node, meta in nodes %}
            {# Open a new list if requested by metadata #}
            {% if meta.open %}
                <ul class="node_tree-list list-unstyled" style="margin-left: 1.5rem;"><li>
            {% else %}
                </li><li>
            {% endif %}

            <a href="{% url 'minisite:node_detail' node.get_path %}">
                {{ node.title }}
            </a>

            {# Close all lists requested by metadata #}
            {% for close in meta.close %}
                </li></ul>
            {% endfor %}
        {% endfor %}
    </div>
{% endif %}

minisite/templates/nodes/index.html
{% extends 'base.html' %}
{% load bootstrap4 %}

{% block page_title %}Home{% endblock %}

{% block content %}

    <!-- Welcome -->
    <div class="jumbotron">
        <h2 class="display-3">Hello!</h2>
        <p class="lead">This is the home page. Please browse the nodes below.</p>
    </div>

    <!-- Nodes -->
    {% if nodes_list %}
        {% include "nodes/fragment-node_tree.html" with nodes=nodes_list only %}
        <p style="margin-left: 1.5rem;">
            <a class="btn btn-primary" href="{% url 'minisite:add' %}">Add new</a>
        </p>
    {% else %}
        <p>Sorry, no nodes</p>
        <p><a class="btn btn-primary" href="{% url 'minisite:add' %}">Add the first one</a></p>
    {% endif %}

{% endblock %}